// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

fetch("/api/foo", {
        method: "POST",
        body: Caml_option.some(JSON.stringify(null)),
        headers: {
          "Content-type": "application/json"
        }
      }).then(function (response) {
      return response.json();
    });

export {
  
}
/*  Not a pure module */
