// Generated by ReScript, PLEASE EDIT WITH CARE


function classify(value) {
  if (typeof value === "string") {
    return {
            NAME: "String",
            VAL: value
          };
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "Fetch_FormData.res",
          10,
          6
        ],
        Error: new Error()
      };
}

var EntryValue = {
  classify: classify
};

var $$Blob;

export {
  $$Blob ,
  EntryValue ,
}
/* No side effect */
