// Generated by ReScript, PLEASE EDIT WITH CARE


var Init = {};

var Body = {
  Init: Init
};

var Init$1 = {};

var $$Headers = {
  Init: Init$1
};

var $$Request = {};

var $$Response = {};

var $$AbortController;

var $$AbortSignal;

var $$Blob;

var $$FormData;

export {
  $$AbortController ,
  $$AbortSignal ,
  $$Blob ,
  $$FormData ,
  Body ,
  $$Headers ,
  $$Request ,
  $$Response ,
}
/* No side effect */
